/**
 * File Content List - action type
 *  - <001> yang berhubungan dengan login dan autentikasi
 *  - <002> yang berhubungan dengan form input
 *  - <2
 */

/**
 * <001>
 */

export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const NOT_LOGIN_YET = 'NOT_LOGIN_YET';

/**
 * <002>
 */
export const NAME_CHANGED = 'NAME_CHANGED';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const CONFIRM_PASSWORD_CHANGED = 'CONFIRM_PASSWORD_CHANGED';

export const NAME_REGISTER_CHANGED = 'NAME_REGISTER_CHANGED';
export const EMAIL_REGISTER_CHANGED = 'EMAIL_REGISTER_CHANGED';
export const PASSWORD_REGISTER_CHANGED = 'PASSWORD_REGISTER_CHANGED';
export const CONFIRM_PASSWORD_REGISTER_CHANGED =
  'CONFIRM_PASSWORD_REGISTER_CHANGED';

export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const ASSIGN_USERDATA_VIEW_KARTUKU = 'ASSIGN_USERDATA_VIEW_KARTUKU';
